config/routes.rb
Rails.application.routes.draw do
  
  # root
  root 'blogs#index'
  
  # root(index)からのcreate(新しい投稿の作成)
  match '/blogs/index' => 'blogs#create', :via => :post
  # root(index)からのいいね
  match '/blogs/likeup' => 'blogs#up_from_index', :via => :post
  
  # showからのいいね
  match '/blogs/show/likeup' => 'blogs#up_from_show', :via => :post
  
  resources :blogs
  
  resources :replies

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  # body should be valid
  # 投稿文字数を140字までに制限する
  validates(:body, presence: true, length: {maximum: 140})
  
end

app/models/reply.rb
class Reply < ApplicationRecord
  
  # add reration
  belongs_to :blog
  
  # comment should be valid
  # 空白文字を許す
  # 投稿文字数を140字までに制限する
  validates(:comment, length: {maximum: 140})
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def index
    @newblog = Blog.new
    @blog = Blog.order('id desc')
    @reply = Reply.all
  end

  def show
    @blogID = params[:id]
    @newreply = Reply.new(blog_id: @blogID)
    @blog = Blog.find(@blogID)
    @reply = Reply.where(blog_id: @blogID)
  end
  
  # 新しい投稿の作成
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to(root_url)
    else
      # 今のところ失敗してもrootに返す仕様
      redirect_to(root_url)
    end
  end
  
  # root(index)からのいいね
  def up_from_index
    @blog = Blog.find(params[:blog][:id])
    @blog.update_attributes(like: @blog.like+1)
    redirect_to(root_path)
  end
  
  # showからのいいね
  def up_from_show
    @blog = Blog.find(params[:blog][:id])
    @blog.update_attributes(like: @blog.like+1)
    redirect_to(blog_path(@blog.id))
  end
  
  # 定義しているだけ
  def edit
  end
  
  # 定義しているだけ
  def update
  end
  
  private
    def blog_params
      params.require(:blog).permit(:body)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
    
    # 新しいコメント作成
    def create
        @reply = Reply.new(reply_params)
        @reply.save
        # @reply.blog_idとして送るが，受け取り方はparams[:id]となる
        redirect_to(blog_path(@reply.blog_id))
    end
    
    private
    def reply_params
      params.require(:reply).permit(:blog_id, :comment)
    end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "InternTest"
    if page_title.empty?
      base_title
    else
    end
  end
  
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/blogs/index.html.erb
<div>
  <%= form_for @newblog, url: blogs_index_path do |b| %>
    <%= b.text_field :body, :size=>"80", :placeholder=>"投稿しよう" %>
    <%= b.submit "投稿する" %>
  <% end %>
</div>
<hr class="noshade">

<div class="pad-left">
  <% @blog.each do |b| %>
      <contribution>
        <%= b.id %>:
        <u>
          <%= link_to b.body, blog_path(b) %>
        </u>
      </contribution><br>
      <u>
        <%= link_to "いいね", blogs_likeup_path(b, params: {blog: {id: b.id}}),
        :method => :post %>
      </u>
        : <%= b.like %> | コメント数:<%= @reply.where(blog_id: b.id).count %> | 
      <t_color class="gray">
        投稿日時: 
        <time>
          <%= b.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %T") %>
        </time>
      </t_color><hr>
  <% end %>
</div>

app/views/blogs/show.html.erb
<u>
    <%= link_to "戻る", root_path %>
</u>

<hr>

<div class="pad-left">
    <%= @blog.id %>: 
    <t_color class="gray">
        投稿日時:<%= @blog.created_at.in_time_zone('Tokyo')
        .strftime("%Y/%m/%d %T") %> 
    </t_color>
    | 
    <u>
        <%= link_to "いいね", blogs_show_likeup_path(@blog, 
            params: { blog: {id: @blog.id} }),
            :method => :post %>
    </u>
    :<%= @blog.like %>
    
</div>

<contribution>
    <div class="pad-left">
        <%= @blog.body %>
    </div>
</contribution>

<br>

<div>
  <%= form_for(@newreply) do |r| %>
    <%= r.hidden_field :blog_id %>
    <%= r.text_field :comment, :size=>"80", :placeholder=>"コメントしよう" %>
    <%= r.submit "コメントする" %>
  <% end %>
</div>

<hr class="noshade">

<div class="pad-left">
    <% @reply.reverse.each do |r| %>
        <reply>
            <%= r.comment %>
        </reply>
          | 
        <t_color class="gray">
            投稿日時: <%= r.created_at.in_time_zone('Tokyo').
            strftime("%Y/%m/%d %T") %>
        </t_color><hr>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <h1>MiniMini blog</h1>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', 
      media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 
      'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>